version: "3"

services:
  game-calendar-reactjs:
    container_name: game-calendar-reactjs
    image: game-calendar-reactjs
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3001:3001
    networks:
      game-calendar:
        ipv4_address: 172.20.0.3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gamecal.rule=Host(`gamecal.sb-pro.fr`)"
      - "traefik.http.routers.gamecal.entrypoints=websecure"
      - "traefik.http.routers.gamecal.tls.certresolver=myresolver"

# docker network create -d bridge --subnet=172.20.0.0/16 --gateway=172.20.0.1 game-calendar
networks:
  game-calendar:
    external: true